### ISSUE TITLE
Regarding Input data and sample data

### ISSUE THREAD

**Issue by jaeneung** [seongsilheo/stress_classification_with_PPG#1]
Hello.

Your paperwork and code are interesting. 

I try to run your code to study it but there is some problem.

1. Sample data for input(feature extraction) or size of input data. 
2. There is no read me file to run this code.

Thank you for reading.

**Comment by seongsilheo** [comment]
Hello jaeneung,

I have edited some code and updated the READEME.md file. Please let me know if you have any problems.
